### ISSUE TITLE
Debugging help...Not really an issue...

### ISSUE THREAD

**Issue by manu144x** [CosmicMac/M5Spot#1]
Hello, I installed this on my M5Stack and works nice, but not everything works, probably some things changed with Spotify API. I want to develop it more but I can't figure out how to debugging. 

I'm not an advanced developer when it comes to IOT, I'm coming from mostly web environments.

I can't figure out how to enable debugging, all I see is garbled stuff in the serial monitor.

Is there something I'm missing?

Thank you.

**Comment by manu144x** [comment]
Nevermind, I found it myself, for some reason it was defaulted to 9600 but in reality it needs to be 115200.

I set it in platformio.ini:
monitor_speed = 115200

All works good

**Comment by CosmicMac** [comment]
Great, thank you for your interest in this little thingy. Wish you a lot of fun with IOT!
